apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: authz
configMapGenerator:
  - name: authz-config
    literals:
      - PORT=8080

